"""Removed external_id

Revision ID: fedf61bedc5e
Revises: fc92ae2298f4
Create Date: 2025-07-10 17:35:23.937304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedf61bedc5e'
down_revision: Union[str, Sequence[str], None] = 'fc92ae2298f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=1)
    # ### end Alembic commands ###
